#!/usr/bin/env bash
# Shared helpers for W2 desk profiles (engineer, overseer, planner).
# Sourced by setup-*-w2.sh — not executed directly.
set -euo pipefail

desk_w2_init() {
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
  REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
  SKILLS_SRC="$REPO_ROOT/skills"
  export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
  PROFILES_DIR="$HERMES_HOME/profiles"
  TEMPLATE="$SCRIPT_DIR/profiles_role.env.template"
  MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"
  command -v hermes >/dev/null || { echo "FATAL: hermes not on PATH" >&2; exit 66; }
  OPENROUTER_KEY=""
  if [[ -f "$HOME/.hermes/profiles/flint/.env" ]]; then
    OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$HOME/.hermes/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
  fi
  [[ -n "$OPENROUTER_KEY" ]] || OPENROUTER_KEY="__SET_ME__"
}

desk_w2_log() { printf '[setup-desk-w2] %s\n' "$*"; }

desk_w2_create_profile() {
  local name="$1" desc="$2"
  if hermes profile list 2>/dev/null | grep -qE "^\s*${name}\b"; then
    desk_w2_log "profile $name exists"
  else
    hermes profile create "$name" --no-skills --no-alias --description "$desc" >/dev/null
    desk_w2_log "created profile $name"
  fi
}

desk_w2_write_config() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by setup-*-w2.sh — desk role (no in-world bot).

model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli

agent:
  max_turns: 200
  gateway_timeout: 1800
  api_max_retries: 3

context:
  engine: compressor
compression:
  enabled: true
  threshold: 0.7
  target_ratio: 0.3
  protect_first_n: 3
  protect_last_n: 20
  abort_on_summary_failure: false

memory:
  memory_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  user_profile_enabled: true
  flush_min_turns: 6
  nudge_interval: 10

tool_output:
  max_bytes: 50000
  max_line_length: 2000
  max_lines: 2000

prompt_caching:
  cache_ttl: 5m

terminal:
  backend: local
  env_passthrough:
    - HERMESCRAFT_REPO
    - HERMES_KANBAN_DB
    - HERMES_KANBAN_ROOT
    - HERMES_KANBAN_WORKSPACES_ROOT
    - HERMES_KANBAN_BOARD
    - HERMES_HOME
EOF
  desk_w2_log "wrote $path"
}

desk_w2_write_env() {
  local name="$1"
  local path="$PROFILES_DIR/$name/.env"
  [[ -f "$TEMPLATE" ]] || { echo "missing $TEMPLATE" >&2; exit 1; }
  {
    sed "s|__OPENROUTER_API_KEY__|$OPENROUTER_KEY|" "$TEMPLATE"
    echo "HERMESCRAFT_REPO=$REPO_ROOT"
  } > "$path"
  chmod 600 "$path"
  desk_w2_log "wrote $path (HERMESCRAFT_REPO + OPENROUTER)"
}

desk_w2_install_skill() {
  local name="$1" src="$2" dest_rel="$3"
  [[ -f "$src" ]] || { echo "missing skill $src" >&2; exit 1; }
  mkdir -p "$PROFILES_DIR/$name/skills/$dest_rel"
  cp "$src" "$PROFILES_DIR/$name/skills/$dest_rel/SKILL.md"
}

desk_w2_zero_memory() {
  local name="$1"
  mkdir -p "$PROFILES_DIR/$name/memories"
  : > "$PROFILES_DIR/$name/memories/MEMORY.md"
}
