#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Local HermesCraft Paper server — one-time setup (idempotent).
# Installs Paper + Multiverse-Core, configures offline bots + native TCP rcon,
# and creates the WORLDS the test/dev paths expect.
#
# Usage:  server/local-setup.sh
#         JAVA_XMX=6G server/local-setup.sh     # override heap
#
# Safe to re-run: skips downloads/worlds that already exist.
# ═══════════════════════════════════════════════════════════════
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/local-common.sh"

echo "── HermesCraft local server setup (Paper $PAPER_VERSION) ──"

# ── 1. Prerequisites ──
command -v java >/dev/null || die "java not found (need JRE 21 for Paper $PAPER_VERSION)"
command -v curl >/dev/null || die "curl not found"
[ -n "$PY" ] || die "python3 not found"
"$PY" -c "import mcrcon" 2>/dev/null || die "python 'mcrcon' missing — run: uv pip install --python .venv -r requirements-dev.txt"
log "java: $(java -version 2>&1 | head -1)"

mkdir -p "$SERVER_DIR" "$PLUGINS_DIR" "$PASS_DIR" "$(dirname "$LOG_FILE")"

# ── 2. rcon password (generate once, persist outside the repo) ──
if [ ! -f "$PASS_FILE" ]; then
  head -c 18 /dev/urandom | base64 | tr -d '/+=' | head -c 24 > "$PASS_FILE"
  chmod 600 "$PASS_FILE"
  log "generated rcon password → $PASS_FILE"
else
  log "rcon password present → $PASS_FILE"
fi
RCON_PASS_VALUE="$(read_rcon_pass)"

# ── 3. Paper jar (latest build for the pinned version) ──
if [ -f "$PAPER_JAR" ]; then
  log "paper.jar present (skip download)"
else
  log "resolving latest Paper $PAPER_VERSION build…"
  read -r BUILD URL < <("$PY" - "$PAPER_VERSION" <<'PY'
import json, sys, urllib.request
ver = sys.argv[1]
api = f"https://api.papermc.io/v2/projects/paper/versions/{ver}"
builds = json.load(urllib.request.urlopen(api, timeout=30))["builds"]
b = builds[-1]
dl = f"{api}/builds/{b}/downloads/paper-{ver}-{b}.jar"
print(b, dl)
PY
)
  log "downloading Paper $PAPER_VERSION build $BUILD"
  curl -fsSL --retry 3 -o "$PAPER_JAR" "$URL" || die "Paper download failed"
  log "→ $PAPER_JAR"
fi

# ── 4. Multiverse-Core plugin (named worlds + world-gen) ──
if compgen -G "$PLUGINS_DIR/[Mm]ultiverse-[Cc]ore*.jar" >/dev/null; then
  log "Multiverse-Core present (skip download)"
else
  log "resolving Multiverse-Core for Paper $PAPER_VERSION (Modrinth)…"
  read -r MV_NAME MV_URL < <("$PY" - "$PAPER_VERSION" <<'PY'
import json, sys, urllib.parse, urllib.request
ver = sys.argv[1]
q = urllib.parse.urlencode({"loaders": '["paper"]', "game_versions": f'["{ver}"]'})
api = f"https://api.modrinth.com/v2/project/multiverse-core/version?{q}"
req = urllib.request.Request(api, headers={"User-Agent": "hermescraft-local-setup"})
versions = json.load(urllib.request.urlopen(req, timeout=30))
if not versions:
    sys.exit(f"no Multiverse-Core version for {ver}")
# Pin to a stable release: the destructive mv world-gen flow is validated
# against 5.6.x stable, not pre-releases.
stable = [v for v in versions if v.get("version_type") == "release"]
chosen = (stable or versions)[0]
files = chosen["files"]
f = next((x for x in files if x.get("primary")), files[0])
print(f["filename"], f["url"])
PY
)
  log "downloading $MV_NAME"
  curl -fsSL --retry 3 -o "$PLUGINS_DIR/$MV_NAME" "$MV_URL" || die "Multiverse-Core download failed"
  log "→ $PLUGINS_DIR/$MV_NAME"
fi

# ── 5. eula + server.properties ──
echo "eula=true" > "$SERVER_DIR/eula.txt"

cat > "$SERVER_DIR/server.properties" <<EOF
# Generated by server/local-setup.sh — local HermesCraft dev server.
online-mode=false
enable-rcon=true
rcon.port=$RCON_PORT
rcon.password=$RCON_PASS_VALUE
broadcast-rcon-to-ops=false
server-port=$MC_PORT
server-ip=127.0.0.1
level-name=world
motd=HermesCraft local dev
spawn-protection=0
allow-nether=true
enable-command-block=true
view-distance=10
simulation-distance=10
max-players=20
gamemode=survival
difficulty=normal
sync-chunk-writes=false
EOF
log "wrote eula.txt + server.properties (offline mode, rcon :$RCON_PORT)"

# ── 6. First boot → create Multiverse worlds → stop ──
log "first boot to generate worlds + load Multiverse (this can take ~30–60s)…"
"$SERVER_DIR/local-start.sh" --no-banner

for w in "${WORLDS[@]}"; do
  # Strip §-color codes before matching (§9landfolk-test breaks grep -w).
  if rcon_cmd "mv list" | sed 's/§.//g' | grep -qiw "$w"; then
    log "world '$w' already exists"
  else
    log "creating world '$w'…"
    rcon_cmd "mv create $w normal" >/dev/null || log "  (mv create $w returned non-zero — check 'mv list')"
    sleep 2
  fi
done

log "worlds now: $(rcon_cmd 'mv list' | sed 's/§.//g' | tr '\n' ' ')"

# Bot hardening + canonical world settings.
configure_landfolk_test      # gamerules, spawn, platform, forceload
patch_spigot_movement        # movement anti-cheat (live reload)
patch_bukkit_throttle        # connection-throttle 0 (next start)
op_configured_players        # op OP_PLAYERS if set

"$SERVER_DIR/local-stop.sh"

echo
echo "  ✓ Local server ready."
echo "    Start:  server/local-start.sh        (or scripts/local-up.sh for server + Tester bot)"
echo "    Stop:   server/local-stop.sh"
echo "    rcon:   server/rcon.sh \"list\""
echo "    Tests:  HERMESCRAFT_PROFILE=local pytest -m 'functional and not slow and not colony'"
