#!/usr/bin/env bash
# Install the pilot-mox profile into the LIVE HERMES_HOME so the wheat
# capstone (Session 5b) is dashboard-visible. Mirrors
# setup-pilot-pip-zee-live.sh's structure but creates ONE mox-bound
# profile that plays four roles per card (@navigator @builder @farmer
# @crafter) instead of two pilot profiles.
#
# Single profile + per-card --skill flags is the same shape the
# two-bot demo used internally (pilot-pip and pilot-zee both played
# multiple roles via per-card skill bundles). The wheat capstone keeps
# the role distinction in the body @-mention and the per-card --skill
# payload; the [bot:mox] title prefix is what mutex_key.py reads to
# serialise on the one shared body.
#
# Idempotent: safe to re-run.
#
# Plan: reports/agent-arch/2026-06-06-colony-validation-plan.md
#
# After this runs:
#   HERMES_HOME=~/.hermes python prototypes/agent-arch/capstone/run_wheat_capstone.py \
#     --run-id trial-$(date +%s) --board wheat-capstone --assignee pilot-mox --watch

set -euo pipefail

MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"

# THIS script targets the LIVE home so cards are dashboard-visible.
export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"

if [[ ! -d "$HERMES_HOME" ]]; then
  echo "FATAL: HERMES_HOME does not exist: $HERMES_HOME" >&2
  exit 66
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
PROFILES_DIR="$HERMES_HOME/profiles"

log() { printf '[setup-mox-live] %s\n' "$*"; }
warn() { printf '[setup-mox-live] WARN: %s\n' "$*" >&2; }
die() { printf '[setup-mox-live] ERROR: %s\n' "$*" >&2; exit 1; }

command -v hermes >/dev/null || die "hermes CLI not on PATH"
[ -d "$SKILLS_SRC" ] || die "skills source not found at $SKILLS_SRC"

# Skill source map — all four role bundles + the four minecraft
# domain bundles + kanban-worker. The runner only loads the relevant
# bundles per card; staging everything makes the per-card --skill
# flags resolve cleanly at create time.
SKILL_SOURCES=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$SKILLS_SRC/agent-navigator.md:gaming/agent-navigator"
  "$SKILLS_SRC/agent-builder.md:gaming/agent-builder"
  "$SKILLS_SRC/agent-farmer.md:gaming/agent-farmer"
  "$SKILLS_SRC/agent-crafter.md:gaming/agent-crafter"
  "$SKILLS_SRC/minecraft-navigation.md:gaming/minecraft-navigation"
  "$SKILLS_SRC/minecraft-building.md:gaming/minecraft-building"
  "$SKILLS_SRC/minecraft-farming.md:gaming/minecraft-farming"
  "$SKILLS_SRC/minecraft-chores.md:gaming/minecraft-chores"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)
for spec in "${SKILL_SOURCES[@]}"; do
  src="${spec%%:*}"
  [ -f "$src" ] || die "missing skill source: $src"
done

# Borrow OpenRouter key from live flint profile.
OPENROUTER_KEY=""
if [ -f "$HOME/.hermes/profiles/flint/.env" ]; then
  OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$HOME/.hermes/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
fi
if [ -z "$OPENROUTER_KEY" ]; then
  warn "no OPENROUTER_API_KEY in flint/.env — pilot-mox .env will use a placeholder. Edit before trial."
  OPENROUTER_KEY="__SET_ME__"
fi

create_profile() {
  local name="$1" description="$2"
  if hermes profile list 2>/dev/null | grep -qE "^\s*$name\b"; then
    log "profile $name already exists — skipping create"
  else
    log "creating profile $name in $HERMES_HOME"
    hermes profile create "$name" --no-skills --no-alias --description "$description" >/dev/null
  fi
}

write_config_yaml() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by setup-pilot-mox-live.sh — do not hand-edit.

model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli

agent:
  max_turns: 200
  gateway_timeout: 1800
  api_max_retries: 3

context:
  engine: compressor
compression:
  enabled: true
  threshold: 0.7
  target_ratio: 0.3
  protect_first_n: 3
  protect_last_n: 20
  abort_on_summary_failure: false

memory:
  memory_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  user_profile_enabled: true
  flush_min_turns: 6
  nudge_interval: 10

tool_output:
  max_bytes: 50000
  max_line_length: 2000
  max_lines: 2000

prompt_caching:
  cache_ttl: 5m

terminal:
  backend: local
  env_passthrough:
    - MC_API_URL
    - MC_USERNAME
    - _MC_API_URL_LOCKED
    - HERMES_KANBAN_DB
    - HERMES_KANBAN_ROOT
    - HERMES_KANBAN_WORKSPACES_ROOT
    - HERMES_HOME
EOF
  log "wrote $path"
}

write_env_from_template() {
  local name="$1" template="$2"
  local path="$PROFILES_DIR/$name/.env"
  [ -f "$template" ] || die "env template missing: $template"
  sed "s|__OPENROUTER_API_KEY__|$OPENROUTER_KEY|" "$template" > "$path"
  chmod 600 "$path"
  log "wrote $path"
}

install_skills() {
  local name="$1"
  shift
  for spec in "$@"; do
    local src="${spec%%:*}"
    local dest_rel="${spec##*:}"
    local dest_dir="$PROFILES_DIR/$name/skills/$dest_rel"
    [ -f "$src" ] || { warn "skipping missing skill source: $src"; continue; }
    mkdir -p "$dest_dir"
    cp "$src" "$dest_dir/SKILL.md"
  done
  log "installed ${#@} skill bundles into $name"
}

write_soul() {
  local name="$1"
  local path="$PROFILES_DIR/$name/SOUL.md"
  cat > "$path" <<'EOF'
# pilot-mox (wheat-farm capstone profile — LIVE HERMES_HOME)

You drive the **Mox** Mineflayer bot. Your MC env (`MC_API_URL`,
`MC_USERNAME`) is pinned in this profile's `.env` so every `mc` call
lands on Mox and only Mox.

You are a kanban worker on the **wheat-capstone** board. Cards come
from `prototypes/agent-arch/capstone/wheat_graph.py` and carry a
`[bot:mox] <slug>` title. Read which role each card asks (@navigator,
@builder, @farmer, @crafter from the body) and load that role's
bundle.

## Turn 1

Call `skill_view('agent-<role>')` where <role> is one of:
navigator, builder, farmer, crafter. Then `mc status` to confirm
position + inventory before starting work.

## Talking to the world

`$MC_API_URL` is pinned to Mox's port (:3007). Always use the `mc`
CLI — direct HTTP calls bypass the pinning.

## Working at marks — read the coords, never guess from the name

Cards address places by mark name (e.g. `:wheat_plot:`, `:wheat_chest:`).
**Mark names are opaque labels.** Do not infer direction, region, or
"near base" semantics from the name's spelling — there is no base, and
the bot has no shared geographic context with you the model.

Before every navigation:

  1. `mc marks` to list marks Mox can see.
  2. `mc inspect --mark <name>` to read the exact coords (x, y, z) of
     the mark the card references.
  3. `mc move <x> <y> <z>` to actually go there.

If `mc marks` does NOT show the mark the card asks for, the trial
setup is broken — `kanban_block` with reason "mark `<name>` not in
mc marks output" and stop. Do NOT invent coords or pick a similar-
sounding mark.

## Block, don't retry

Verb fails twice without progress → `kanban_block` with a structured
reason from the role bundle's §5 ("when to block"). The capstone's
acceptance gate is honest — if the till didn't complete, an honest
block is more useful than a fake "done".

A `kanban_block` is also the right tool when the world isn't shaped
the way the card assumes (missing chest, no water, ravine where dirt
should be) — those are fixture problems, not work problems.
EOF
  log "wrote $path"
}

# ── Fresh-trial memory zero ─────────────────────────────────────────
# Every wheat capstone trial must start from a clean memory state.
# Earlier trial memories (e.g. "the wheat_plot mark doesn't exist")
# would prime the next trial with stale beliefs. Truncate MEMORY.md
# at setup time. Operator can also re-run setup before each trial to
# zero it.
zero_memory() {
  local name="$1"
  local mem="$PROFILES_DIR/$name/memories/MEMORY.md"
  if [[ -f "$mem" ]]; then
    : > "$mem"
    log "zeroed $mem"
  fi
}

# ── Install the wheat-harvest-reminder cron script ──────────────────
# Pre-stage the script `hermes cron` will run. Hermes requires cron
# scripts to live under ~/.hermes/scripts/, so we copy from the repo's
# scripts/cron/ directory. Idempotent — overwrites each setup run so
# fixes propagate.
install_cron_scripts() {
  local dest_dir="$HERMES_HOME/scripts"
  mkdir -p "$dest_dir"
  cp "$REPO_ROOT/scripts/cron/wheat-harvest-reminder.sh" \
     "$dest_dir/wheat-harvest-reminder.sh"
  chmod +x "$dest_dir/wheat-harvest-reminder.sh"
  log "installed $dest_dir/wheat-harvest-reminder.sh"
}

# ── Profile creation ────────────────────────────────────────────────

create_profile pilot-mox \
  "Pilot bound to Mox bot (port 3007). Wheat-farm capstone on live HERMES_HOME, dashboard-visible. Plays @navigator @builder @farmer @crafter per card via per-card --skill."
write_config_yaml pilot-mox
write_env_from_template pilot-mox "$SCRIPT_DIR/profiles_pilot-mox.env.template"
install_skills pilot-mox "${SKILL_SOURCES[@]}"
write_soul pilot-mox
zero_memory pilot-mox
install_cron_scripts

# Pre-create the board so the runner's idempotent ensure step is fast.
if hermes kanban boards list 2>/dev/null | grep -qE 'wheat-capstone'; then
  log "board wheat-capstone already exists"
else
  log "creating board wheat-capstone"
  hermes kanban boards create wheat-capstone >/dev/null || \
    warn "board create returned non-zero; runner will retry"
fi

log "done."
log "  HERMES_HOME    = $HERMES_HOME"
log "  profiles dir   = $PROFILES_DIR"
log "  profile        = pilot-mox  (bound to Mox :3007)"
log "  board          = wheat-capstone"
log
log "Session 5b launch (dashboard-visible at http://127.0.0.1:9119):"
log "  HERMES_HOME=$HERMES_HOME \\"
log "    python prototypes/agent-arch/capstone/run_wheat_capstone.py \\"
log "    --run-id trial-\$(date +%s) --board wheat-capstone --assignee pilot-mox --watch"
log
log "Verify profile + skills:"
log "  HERMES_HOME=$HERMES_HOME hermes profile show pilot-mox"
log "  HERMES_HOME=$HERMES_HOME hermes kanban --board wheat-capstone list"
