#!/usr/bin/env bash
# Create the pilot-* profiles for the agent-arch prototype.
#
# Idempotent: safe to re-run. Will not modify existing flint/mason/etc.
# Adds (or refreshes) ~/.hermes/profiles/pilot-navigator/ and
# ~/.hermes/profiles/pilot-miner/ with:
#   - .env containing MC_API_URL (to the mock bot) + OPENROUTER_API_KEY
#     copied from the flint profile (if present) so we don't need a
#     separate secret rotation.
#   - config.yaml pinning model deepseek/deepseek-v4-flash (the same
#     cheap fast tier the existing fleet uses — see flint/config.yaml).
#   - Skills under skills/gaming/ and skills/devops/ in the SKILL.md
#     tree shape that hermes resolves.
#
# Profiles created:
#   pilot-navigator — kanban-worker, agent-navigator, minecraft-navigation,
#                     minecraft-survival
#   pilot-miner     — kanban-worker, agent-miner (Phase 3), minecraft-mining,
#                     minecraft-survival
#
# Run from anywhere; the script resolves the hermescraft repo via its own
# location.

set -euo pipefail

# Defaults
PORT="${PROTO_MOCK_PORT:-3091}"
MC_API_URL="http://127.0.0.1:${PORT}"
MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"
INCLUDE_MINER="${PROTO_INCLUDE_MINER:-1}"

# Isolated HERMES_HOME. Findings from Phase 0: `hermes kanban dispatch` is
# NOT tenant-scoped, so prototype cards on a shared ~/.hermes would be
# claimed by the live dispatcher alongside landfolk-ops cards. The plan's
# Option B (isolated home) is therefore the default — separate kanban DB,
# separate profiles, separate everything.
export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes-proto-agent-arch}"
mkdir -p "$HERMES_HOME"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
PROFILES_DIR="$HERMES_HOME/profiles"
REAL_HOME="$HOME/.hermes"

log() { printf '[setup] %s\n' "$*"; }
warn() { printf '[setup] WARN: %s\n' "$*" >&2; }
die() { printf '[setup] ERROR: %s\n' "$*" >&2; exit 1; }

# ----- pre-flight ---------------------------------------------------------

command -v hermes >/dev/null || die "hermes CLI not on PATH"
[ -d "$SKILLS_SRC" ] || die "skills source not found at $SKILLS_SRC"

# Source skills we need. agent-miner.md lives under prototypes/agent-arch/
# until Phase 3 promotes it; everything else is in the canonical skills/.
NAV_SKILL_SOURCES=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$SKILLS_SRC/agent-navigator.md:gaming/agent-navigator"
  "$SKILLS_SRC/minecraft-navigation.md:gaming/minecraft-navigation"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)
MINER_SKILL_SOURCES=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$REPO_ROOT/prototypes/agent-arch/skills/agent-miner.md:gaming/agent-miner"
  "$SKILLS_SRC/minecraft-mining.md:gaming/minecraft-mining"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)

for spec in "${NAV_SKILL_SOURCES[@]}"; do
  src="${spec%%:*}"
  [ -f "$src" ] || die "missing skill source: $src"
done

# ----- secret reuse -------------------------------------------------------

# Borrow the API key from the real ~/.hermes/profiles/flint/.env so we don't
# have to rotate secrets just to run the prototype.
OPENROUTER_KEY=""
if [ -f "$REAL_HOME/profiles/flint/.env" ]; then
  OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$REAL_HOME/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
fi
if [ -z "$OPENROUTER_KEY" ]; then
  warn "no OPENROUTER_API_KEY found in $REAL_HOME/profiles/flint/.env — pilot profiles will start with an empty key. Set OPENROUTER_API_KEY in $PROFILES_DIR/pilot-*/.env before Phase 1."
fi

# ----- profile creation ---------------------------------------------------

create_profile() {
  local name="$1"
  local description="$2"

  if hermes profile list 2>/dev/null | grep -qE "^\s*$name\b"; then
    log "profile $name already exists — skipping create"
  else
    log "creating profile $name"
    hermes profile create "$name" --no-skills --no-alias --description "$description" >/dev/null
  fi
}

# Pinned config.yaml. Mirrors flint's structure but trimmed to what the
# prototype actually needs.
write_config_yaml() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by prototypes/agent-arch/setup.sh — do not hand-edit.
# Override env vars in .env, not here.
model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli
agent:
  max_turns: 150
  gateway_timeout: 1800
  api_max_retries: 3
EOF
  log "wrote $path"
}

write_env() {
  local name="$1"
  local username="$2"
  local path="$PROFILES_DIR/$name/.env"
  # Preserve any existing keys we didn't write by reading the file first
  # if it exists. Simplest approach: regenerate from known-good template
  # since the prototype profiles are owned by this script.
  cat > "$path" <<EOF
# Generated by prototypes/agent-arch/setup.sh — do not hand-edit.
# Re-run setup.sh to refresh. To change the mock URL, set PROTO_MOCK_PORT
# in the environment when running setup.sh.
MC_API_URL=$MC_API_URL
_MC_API_URL_LOCKED=$MC_API_URL
MC_USERNAME=$username
OPENROUTER_API_KEY=$OPENROUTER_KEY
EOF
  chmod 600 "$path"
  log "wrote $path"
}

install_skills() {
  local name="$1"
  shift
  for spec in "$@"; do
    local src="${spec%%:*}"
    local dest_rel="${spec##*:}"
    local dest_dir="$PROFILES_DIR/$name/skills/$dest_rel"
    if [ ! -f "$src" ]; then
      warn "skipping missing skill source: $src"
      continue
    fi
    mkdir -p "$dest_dir"
    cp "$src" "$dest_dir/SKILL.md"
    log "  installed skill $dest_rel"
  done
}

write_soul() {
  local name="$1"
  local body="$2"
  local path="$PROFILES_DIR/$name/SOUL.md"
  cat > "$path" <<EOF
# $name (prototype profile)

You are a kanban worker on the agent-arch prototype board.

$body

## Turn 1

Call \`skill_view('agent-${name#pilot-}')\` first thing every session.
The skill body contains your verb catalog, scope, done/stop conditions,
and the handoff metadata you must emit on \`kanban_complete\`.

## Talking to the world

The bot HTTP API is at \`\$MC_API_URL\` (already in your env). Use the
\`mc\` CLI — never curl it directly. Do not assume any specific bot is
online; rely on \`mc status\` first to see your position.
EOF
  log "wrote $path"
}

# ----- pilot-navigator ----------------------------------------------------

create_profile pilot-navigator \
  "Navigator agent — moves a Mineflayer bot to a named :mark:. Bot-bound; reads MC_API_URL + MC_USERNAME from env. Phase 1/2 of the agent-arch prototype."
write_config_yaml pilot-navigator
write_env pilot-navigator pip
install_skills pilot-navigator "${NAV_SKILL_SOURCES[@]}"
write_soul pilot-navigator \
  "Your job is one navigation phase per card — move to the :mark: named in the body. Call \`mc status\` then \`mc move @<mark>\` until you arrive. Complete with handoff metadata: exit_pos, exit_facing, stopped_at_mark."

# ----- pilot-miner (Phase 3) ----------------------------------------------

if [ "$INCLUDE_MINER" = "1" ]; then
  if [ ! -f "$REPO_ROOT/prototypes/agent-arch/skills/agent-miner.md" ]; then
    warn "agent-miner.md not authored yet — skipping pilot-miner profile (re-run with PROTO_INCLUDE_MINER=1 after writing prototypes/agent-arch/skills/agent-miner.md)"
  else
    create_profile pilot-miner \
      "Miner agent — extracts resources at a named :mark:. Bot-bound. Phase 3 of the agent-arch prototype."
    write_config_yaml pilot-miner
    write_env pilot-miner pip
    install_skills pilot-miner "${MINER_SKILL_SOURCES[@]}"
    write_soul pilot-miner \
      "Your job is one extraction phase per card — dig the requested count of the requested material at the :mark: named in the body. Complete with handoff metadata: inv_delta, exit_pos, exit_facing, stopped_at_mark."
  fi
fi

log "done."
log "  HERMES_HOME    = $HERMES_HOME"
log "  profiles dir   = $PROFILES_DIR"
log "  pilot profiles = $(ls "$PROFILES_DIR" 2>/dev/null | grep '^pilot-' | tr '\n' ' ')"
log
log "To use these profiles, always export HERMES_HOME=$HERMES_HOME"
log "before running hermes commands (run.sh and dispatch.py do this for you)."
