#!/usr/bin/env bash
# Install W1 execute role profiles under live HERMES_HOME (~/.hermes).
# Idempotent. MC_API_URL/MC_USERNAME ARE in .env — Hermes strips MC_* at
# worker spawn (see kanban_db.py:6671), so the dispatcher-export path is
# architecturally blocked. The role .env is the only working channel
# until W4 needs per-card bot routing.
#
# Usage:
#   HERMES_HOME=~/.hermes prototypes/agent-arch/setup-role-profiles.sh

set -euo pipefail

MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"
export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
KANBAN_BOARD="${KANBAN_BOARD:-wheat-capstone}"

if [[ ! -d "$HERMES_HOME" ]]; then
  echo "FATAL: HERMES_HOME does not exist: $HERMES_HOME" >&2
  exit 66
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
PROFILES_DIR="$HERMES_HOME/profiles"
TEMPLATE="$SCRIPT_DIR/profiles_role.env.template"

log() { printf '[setup-roles] %s\n' "$*"; }
warn() { printf '[setup-roles] WARN: %s\n' "$*" >&2; }
die() { printf '[setup-roles] ERROR: %s\n' "$*" >&2; exit 1; }

command -v hermes >/dev/null || die "hermes CLI not on PATH"

OPENROUTER_KEY=""
if [[ -f "$HOME/.hermes/profiles/flint/.env" ]]; then
  OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$HOME/.hermes/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
fi
if [[ -z "$OPENROUTER_KEY" ]]; then
  warn "no OPENROUTER_API_KEY in flint/.env — edit role .env before live trial"
  OPENROUTER_KEY="__SET_ME__"
fi

create_profile() {
  local name="$1" description="$2"
  if hermes profile list 2>/dev/null | grep -qE "^\s*${name}\b"; then
    log "profile $name exists — skip create"
  else
    hermes profile create "$name" --no-skills --no-alias --description "$description" >/dev/null
    log "created profile $name"
  fi
}

write_config_yaml() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by setup-role-profiles.sh — W1 execute role.

model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli

agent:
  max_turns: 200
  gateway_timeout: 1800
  api_max_retries: 3

context:
  engine: compressor
compression:
  enabled: true
  threshold: 0.7
  target_ratio: 0.3
  protect_first_n: 3
  protect_last_n: 20
  abort_on_summary_failure: false

memory:
  memory_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  user_profile_enabled: true
  flush_min_turns: 6
  nudge_interval: 10

tool_output:
  max_bytes: 50000
  max_line_length: 2000
  max_lines: 2000

prompt_caching:
  cache_ttl: 5m

terminal:
  backend: local
  env_passthrough:
    - MC_API_URL
    - MC_USERNAME
    - _MC_API_URL_LOCKED
    - HERMES_KANBAN_DB
    - HERMES_KANBAN_ROOT
    - HERMES_KANBAN_WORKSPACES_ROOT
    - HERMES_KANBAN_BOARD
    - HERMES_HOME
    - HERMESCRAFT_REPO
EOF
  log "wrote $path"
}

write_env() {
  local name="$1"
  local path="$PROFILES_DIR/$name/.env"
  local api_port user
  api_port=$(awk '/^api_port:/ {print $2}' "$REPO_ROOT/data/bots/mox.yaml")
  user=$(awk '/^username:/ {print $2}' "$REPO_ROOT/data/bots/mox.yaml")
  [[ -f "$TEMPLATE" ]] || die "missing $TEMPLATE"
  {
    sed "s|__OPENROUTER_API_KEY__|$OPENROUTER_KEY|" "$TEMPLATE"
    echo "MC_API_URL=http://127.0.0.1:${api_port}"
    echo "MC_USERNAME=${user}"
    echo "_MC_API_URL_LOCKED=http://127.0.0.1:${api_port}"
    echo "HERMESCRAFT_REPO=$REPO_ROOT"
  } > "$path"
  chmod 600 "$path"
  log "wrote $path (OPENROUTER + Mox MC_* for W1)"
}

install_skills() {
  local name="$1"
  shift
  for spec in "$@"; do
    local src="${spec%%:*}"
    local dest_rel="${spec##*:}"
    [[ -f "$src" ]] || die "missing skill: $src"
    mkdir -p "$PROFILES_DIR/$name/skills/$dest_rel"
    cp "$src" "$PROFILES_DIR/$name/skills/$dest_rel/SKILL.md"
  done
  log "installed skills for $name"
}

install_mc_wrapper() {
  local name="$1"
  local api_port user
  api_port=$(awk '/^api_port:/ {print $2}' "$REPO_ROOT/data/bots/mox.yaml")
  user=$(awk '/^username:/ {print $2}' "$REPO_ROOT/data/bots/mox.yaml")
  local bindir="$PROFILES_DIR/$name/bin"
  mkdir -p "$bindir"
  cat > "$bindir/mc" <<EOF
#!/usr/bin/env bash
# W1-only shim — remove when fleet MC routing is universal (W4).
set -euo pipefail
export MC_API_URL="\${MC_API_URL:-http://127.0.0.1:${api_port}}"
export MC_USERNAME="\${MC_USERNAME:-${user}}"
exec "${REPO_ROOT}/bin/mc" "\$@"
EOF
  chmod +x "$bindir/mc"
  log "installed W1 bin/mc for $name (defaults Mox :${api_port})"
}

write_soul() {
  local name="$1" role="$2" domain_skill="$3"
  local path="$PROFILES_DIR/$name/SOUL.md"
  cat > "$path" <<EOF
# ${name} (execute role — wheat-capstone W1)

You are the **${role}** worker on board **${KANBAN_BOARD}**. Bot HTTP identity
(\`MC_API_URL\`, \`MC_USERNAME\`) is loaded from this profile's \`.env\` at
spawn — \`mc\` will reach Mox (:3007) without any manual export.

## Turn 1

1. When \`HERMES_KANBAN_TASK\` is set, read the active card first:
   \`scripts/kanban card \$HERMES_KANBAN_TASK\` (or \`kanban_show\` equivalent).
2. Load the full card skill bundle (L0–L3):
   \`skill_view('kanban-worker')\`, \`skill_view('agent-${role}')\`,
   \`skill_view('${domain_skill}')\`, \`skill_view('minecraft-survival')\`.
3. Read parent handoff via \`kanban_show\` / parent completion metadata
   (\`exit_pos\`, \`work_at_mark\`).
4. \`mc status\` before acting.

## On kanban_complete

Include metadata at minimum: \`exit_pos\` (from \`mc status\`) and
\`work_at_mark\` when the card names a mark. See agent bundle §7.

## Marks

Use \`mc inspect --mark <name>\` — never guess coords from mark names.
EOF
  log "wrote $path"
}

zero_memory() {
  local name="$1"
  mkdir -p "$PROFILES_DIR/$name/memories"
  : > "$PROFILES_DIR/$name/memories/MEMORY.md"
  log "zeroed $name memories/MEMORY.md"
}

COMMON=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)

setup_role() {
  local role="$1" agent_skill="$2" domain_skill="$3" domain_view="$4" desc="$5"
  create_profile "$role" "$desc"
  write_config_yaml "$role"
  write_env "$role"
  install_skills "$role" \
    "${COMMON[@]}" \
    "$SKILLS_SRC/agent-${agent_skill}.md:gaming/agent-${agent_skill}" \
    "$SKILLS_SRC/${domain_skill}.md:gaming/${domain_skill}"
  write_soul "$role" "$agent_skill" "$domain_view"
  zero_memory "$role"
}

# Navigator also runs proc-nav observe cards (pn-observe) — needs minecraft-observe.
_navigator_skills=("${COMMON[@]}" \
  "$SKILLS_SRC/agent-navigator.md:gaming/agent-navigator" \
  "$SKILLS_SRC/minecraft-navigation.md:gaming/minecraft-navigation" \
  "$SKILLS_SRC/minecraft-observe.md:gaming/minecraft-observe")
create_profile navigator "Navigator execute role (wheat W1)"
write_config_yaml navigator
write_env navigator
install_skills navigator "${_navigator_skills[@]}"
write_soul navigator navigator minecraft-navigation
zero_memory navigator
setup_role builder builder minecraft-building minecraft-building "Builder execute role (wheat W1)"
setup_role farmer farmer minecraft-farming minecraft-farming "Farmer execute role (wheat W1)"
setup_role crafter crafter minecraft-chores minecraft-chores "Crafter execute role (wheat W1)"

if hermes kanban boards list 2>/dev/null | grep -qF "$KANBAN_BOARD"; then
  log "board $KANBAN_BOARD exists"
else
  hermes kanban boards create "$KANBAN_BOARD" >/dev/null 2>&1 || warn "board create non-zero"
fi

log "done. Profiles: navigator builder farmer crafter under $HERMES_HOME"
