#!/usr/bin/env bash
# Create the pilot-pip and pilot-zee profiles for the two-bot live demo.
#
# Idempotent: safe to re-run. Each profile carries:
#   - .env with MC_API_URL pinned to the bot's port (from data/bots/<bot>.yaml)
#     and MC_USERNAME = the bot's in-game name.
#   - config.yaml pinning model `deepseek/deepseek-v4-flash` on BOTH pilots
#     so any wall-time gap between pip's lane and zee's lane can't be
#     confounded by model variance.
#   - The 4 role bundles (agent-navigator/builder/crafter/miner) + the 4
#     supporting minecraft-* skills + kanban-worker. Both pilots can play
#     any role; the SOUL says which roles are common.
#
# These profiles live under HERMES_HOME=~/.hermes-proto-agent-arch so they
# never collide with the live ~/.hermes/profiles/{flint,...} fleet.
#
# Plan: ~/.claude/plans/create-a-plan-that-magical-lovelace.md (Phase 3).

set -euo pipefail

MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"

export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes-proto-agent-arch}"
mkdir -p "$HERMES_HOME"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
PROFILES_DIR="$HERMES_HOME/profiles"
REAL_HOME="$HOME/.hermes"

log() { printf '[setup-pp] %s\n' "$*"; }
warn() { printf '[setup-pp] WARN: %s\n' "$*" >&2; }
die() { printf '[setup-pp] ERROR: %s\n' "$*" >&2; exit 1; }

# ── Preconditions ───────────────────────────────────────────────────
command -v hermes >/dev/null || die "hermes CLI not on PATH"
[ -d "$SKILLS_SRC" ] || die "skills source not found at $SKILLS_SRC"

# Skill source map. Every pilot gets the union — they may play any role.
# Format: <source-path>:<destination-relative-path>
SKILL_SOURCES=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$SKILLS_SRC/agent-navigator.md:gaming/agent-navigator"
  "$SKILLS_SRC/agent-builder.md:gaming/agent-builder"
  "$SKILLS_SRC/agent-crafter.md:gaming/agent-crafter"
  "$SKILLS_SRC/agent-miner.md:gaming/agent-miner"
  "$SKILLS_SRC/minecraft-navigation.md:gaming/minecraft-navigation"
  "$SKILLS_SRC/minecraft-building.md:gaming/minecraft-building"
  "$SKILLS_SRC/minecraft-chores.md:gaming/minecraft-chores"
  "$SKILLS_SRC/minecraft-mining.md:gaming/minecraft-mining"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)
for spec in "${SKILL_SOURCES[@]}"; do
  src="${spec%%:*}"
  [ -f "$src" ] || die "missing skill source: $src"
done

# ── Borrow OpenRouter key from the live flint profile ───────────────
OPENROUTER_KEY=""
if [ -f "$REAL_HOME/profiles/flint/.env" ]; then
  OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$REAL_HOME/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
fi
if [ -z "$OPENROUTER_KEY" ]; then
  warn "no OPENROUTER_API_KEY found in $REAL_HOME/profiles/flint/.env — pilot .env files will have a placeholder. Edit them before running the trial."
  OPENROUTER_KEY="__SET_ME__"
fi

# ── Helpers ─────────────────────────────────────────────────────────

create_profile() {
  local name="$1" description="$2"
  if hermes profile list 2>/dev/null | grep -qE "^\s*$name\b"; then
    log "profile $name already exists — skipping create"
  else
    log "creating profile $name"
    hermes profile create "$name" --no-skills --no-alias --description "$description" >/dev/null
  fi
}

write_config_yaml() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by setup-pilot-pip-zee.sh — do not hand-edit.
# Override env vars in .env, not here.
model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli
agent:
  max_turns: 200
  gateway_timeout: 1800
  api_max_retries: 3
EOF
  log "wrote $path"
}

write_env_from_template() {
  local name="$1" template="$2"
  local path="$PROFILES_DIR/$name/.env"
  if [ ! -f "$template" ]; then
    die "env template missing: $template"
  fi
  sed "s|__OPENROUTER_API_KEY__|$OPENROUTER_KEY|" "$template" > "$path"
  chmod 600 "$path"
  log "wrote $path"
}

install_skills() {
  local name="$1"
  shift
  for spec in "$@"; do
    local src="${spec%%:*}"
    local dest_rel="${spec##*:}"
    local dest_dir="$PROFILES_DIR/$name/skills/$dest_rel"
    [ -f "$src" ] || { warn "skipping missing skill source: $src"; continue; }
    mkdir -p "$dest_dir"
    cp "$src" "$dest_dir/SKILL.md"
  done
  log "installed ${#@} skill bundles into $name"
}

write_soul() {
  local name="$1" body_name="$2"
  local path="$PROFILES_DIR/$name/SOUL.md"
  cat > "$path" <<EOF
# $name (two-bot demo profile)

You drive the **$body_name** Mineflayer bot. Your MC env (\`MC_API_URL\`,
\`MC_USERNAME\`) is pinned in this profile's \`.env\` so every \`mc\` call
lands on $body_name and only $body_name.

You are a kanban worker on the proto-agent-arch tenant for the two-bot
cooperative-base demo. The card you're claiming names a role
(@navigator, @builder, @crafter, or @miner) via the title prefix
\`[bot:$body_name]\`. Your turn-1 job is to read which role this card
asks you to play and load that role's bundle.

## Turn 1

Read the card title and body. Call:

  \`skill_view('agent-<role>')\`

where <role> is one of: navigator, builder, crafter, miner. The role
bundle defines what you do, what you don't, when you stop, and what
handoff metadata you must emit on \`kanban_complete\`.

Then call \`mc status\` to confirm your position and inventory match the
parent card's handoff.

## Talking to the world

The bot HTTP API is at \`\$MC_API_URL\` (already in your env). Always
use the \`mc\` CLI — never curl directly. The bot HTTP is bound to
$body_name; running \`mc\` against it commands $body_name's body.

## Cooperation

You are one of two pilots in this demo. The other bot (the partner)
runs its own lane. Your card metadata may depend on the partner's
completion — read parent handoff metadata for \`exit_pos\`, \`inv_delta\`,
\`work_at_mark\` before acting. If a parent isn't done yet, the
mutex/parent-link kept this card in \`blocked\` until now; trust it.

## Block, don't retry

If a verb fails twice without progress, **block the card** with a
structured reason from the role bundle's §5 escape rules. The other
bot's lane stays productive while an operator (or @overseer in a later
session) addresses your block.
EOF
  log "wrote $path"
}

# ── Profile creation ────────────────────────────────────────────────

# pilot-pip — bot Pip, port 3005
create_profile pilot-pip \
  "Pilot bound to bot Pip (port 3005). Two-bot demo. Plays @navigator, @builder, @crafter, @miner per card."
write_config_yaml pilot-pip
write_env_from_template pilot-pip "$SCRIPT_DIR/profiles_pilot-pip.env.template"
install_skills pilot-pip "${SKILL_SOURCES[@]}"
write_soul pilot-pip Pip

# pilot-zee — bot Zee, port 3006
create_profile pilot-zee \
  "Pilot bound to bot Zee (port 3006). Two-bot demo. Plays @navigator, @builder, @crafter, @miner per card."
write_config_yaml pilot-zee
write_env_from_template pilot-zee "$SCRIPT_DIR/profiles_pilot-zee.env.template"
install_skills pilot-zee "${SKILL_SOURCES[@]}"
write_soul pilot-zee Zee

log "done."
log "  HERMES_HOME    = $HERMES_HOME"
log "  profiles dir   = $PROFILES_DIR"
log "  pilots created = pilot-pip pilot-zee"
log
log "Verify:"
log "  HERMES_HOME=$HERMES_HOME hermes profile show pilot-pip --json"
log "  HERMES_HOME=$HERMES_HOME hermes profile show pilot-zee --json"
