#!/usr/bin/env bash
# Install pilot-pip and pilot-zee profiles into the LIVE HERMES_HOME
# (~/.hermes/profiles/) so trial 3 cards are visible on the existing
# :9119 dashboard.
#
# Same skill bundles + env + model as setup-pilot-pip-zee.sh, but:
#   - HERMES_HOME=~/.hermes (the live one — the dashboard reads it)
#   - Cards will land on a custom board (--board two-bot-demo) to
#     keep them isolated from landfolk-ops (which the live dispatcher
#     claims with --board landfolk-ops)
#   - Workspaces will live at ~/.hermes/kanban/boards/two-bot-demo/workspaces/
#     (the newer boards layout, not the flat proto layout)
#
# Idempotent: safe to re-run; overwrites config.yaml + SOUL.md + .env each
# time so config tweaks land.
#
# Plan: ~/.claude/plans/create-a-plan-that-magical-lovelace.md
# Postmortem: reports/agent-arch/2026-06-07-two-bot-trial-2-postmortem.md
#
# After this runs, launch trial 3 with:
#
#   HERMES_HOME=~/.hermes python prototypes/agent-arch/capstone/run_two_bot_base.py \
#     --run-id trial-$(date +%s) --board two-bot-demo --watch

set -euo pipefail

MODEL_DEFAULT="${PROTO_MODEL:-deepseek/deepseek-v4-flash}"

# THIS script targets the LIVE home so cards are dashboard-visible.
# (setup-pilot-pip-zee.sh — the proto-isolated sibling — targets
#  ~/.hermes-proto-agent-arch instead.)
export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"

if [[ ! -d "$HERMES_HOME" ]]; then
  echo "FATAL: HERMES_HOME does not exist: $HERMES_HOME" >&2
  echo "       This script targets the LIVE Hermes install. If you want the" >&2
  echo "       proto-isolated rig, use setup-pilot-pip-zee.sh instead." >&2
  exit 66
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_SRC="$REPO_ROOT/skills"
PROFILES_DIR="$HERMES_HOME/profiles"

log() { printf '[setup-pp-live] %s\n' "$*"; }
warn() { printf '[setup-pp-live] WARN: %s\n' "$*" >&2; }
die() { printf '[setup-pp-live] ERROR: %s\n' "$*" >&2; exit 1; }

command -v hermes >/dev/null || die "hermes CLI not on PATH"
[ -d "$SKILLS_SRC" ] || die "skills source not found at $SKILLS_SRC"

# Safety check: refuse to overwrite a live flint profile or other established
# bots accidentally. We only own pilot-* profile names.
for safety_check in pilot-pip pilot-zee; do
  if [[ -d "$PROFILES_DIR/$safety_check" ]]; then
    log "$safety_check already exists at $PROFILES_DIR/$safety_check — will refresh config + SOUL only, leaving any persisted state alone."
  fi
done

# Skill source map — same as the proto setup so the bundles match.
SKILL_SOURCES=(
  "$SKILLS_SRC/kanban-worker.md:devops/kanban-worker"
  "$SKILLS_SRC/agent-navigator.md:gaming/agent-navigator"
  "$SKILLS_SRC/agent-builder.md:gaming/agent-builder"
  "$SKILLS_SRC/agent-crafter.md:gaming/agent-crafter"
  "$SKILLS_SRC/agent-miner.md:gaming/agent-miner"
  "$SKILLS_SRC/minecraft-navigation.md:gaming/minecraft-navigation"
  "$SKILLS_SRC/minecraft-building.md:gaming/minecraft-building"
  "$SKILLS_SRC/minecraft-chores.md:gaming/minecraft-chores"
  "$SKILLS_SRC/minecraft-mining.md:gaming/minecraft-mining"
  "$SKILLS_SRC/minecraft-survival.md:gaming/minecraft-survival"
)
for spec in "${SKILL_SOURCES[@]}"; do
  src="${spec%%:*}"
  [ -f "$src" ] || die "missing skill source: $src"
done

# Borrow the OpenRouter key from the live flint profile (same trick as
# the proto setup).
OPENROUTER_KEY=""
if [ -f "$HOME/.hermes/profiles/flint/.env" ]; then
  OPENROUTER_KEY="$(grep -E '^OPENROUTER_API_KEY=' "$HOME/.hermes/profiles/flint/.env" | head -1 | sed 's/^OPENROUTER_API_KEY=//' || true)"
fi
if [ -z "$OPENROUTER_KEY" ]; then
  warn "no OPENROUTER_API_KEY found in $HOME/.hermes/profiles/flint/.env — pilot .env files will use a placeholder. Edit them before trial 3."
  OPENROUTER_KEY="__SET_ME__"
fi

# Helpers (mirror setup-pilot-pip-zee.sh; consolidated here to avoid an
# import chain in shell).

create_profile() {
  local name="$1" description="$2"
  if hermes profile list 2>/dev/null | grep -qE "^\s*$name\b"; then
    log "profile $name already exists — skipping create"
  else
    log "creating profile $name in $HERMES_HOME"
    hermes profile create "$name" --no-skills --no-alias --description "$description" >/dev/null
  fi
}

write_config_yaml() {
  local name="$1"
  local path="$PROFILES_DIR/$name/config.yaml"
  cat > "$path" <<EOF
# Generated by setup-pilot-pip-zee-live.sh — do not hand-edit.
# Override env vars in .env, not here.
#
# Mirrors the proto pilot config (compression on, memory tuned, tool_output
# capped) so behaviour matches between proto and live runs.

model:
  context_length: 250000
  default: $MODEL_DEFAULT
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
providers: {}
toolsets:
  - hermes-cli

agent:
  max_turns: 200
  gateway_timeout: 1800
  api_max_retries: 3

context:
  engine: compressor
compression:
  enabled: true
  threshold: 0.7
  target_ratio: 0.3
  protect_first_n: 3
  protect_last_n: 20
  abort_on_summary_failure: false

memory:
  memory_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  user_profile_enabled: true
  flush_min_turns: 6
  nudge_interval: 10

tool_output:
  max_bytes: 50000
  max_line_length: 2000
  max_lines: 2000

prompt_caching:
  cache_ttl: 5m

terminal:
  backend: local
  env_passthrough:
    - MC_API_URL
    - MC_USERNAME
    - _MC_API_URL_LOCKED
    - HERMES_KANBAN_DB
    - HERMES_KANBAN_ROOT
    - HERMES_KANBAN_WORKSPACES_ROOT
    - HERMES_HOME
EOF
  log "wrote $path"
}

write_env_from_template() {
  local name="$1" template="$2"
  local path="$PROFILES_DIR/$name/.env"
  if [ ! -f "$template" ]; then
    die "env template missing: $template"
  fi
  sed "s|__OPENROUTER_API_KEY__|$OPENROUTER_KEY|" "$template" > "$path"
  chmod 600 "$path"
  log "wrote $path"
}

install_skills() {
  local name="$1"
  shift
  for spec in "$@"; do
    local src="${spec%%:*}"
    local dest_rel="${spec##*:}"
    local dest_dir="$PROFILES_DIR/$name/skills/$dest_rel"
    [ -f "$src" ] || { warn "skipping missing skill source: $src"; continue; }
    mkdir -p "$dest_dir"
    cp "$src" "$dest_dir/SKILL.md"
  done
  log "installed ${#@} skill bundles into $name"
}

write_soul() {
  local name="$1" body_name="$2"
  local path="$PROFILES_DIR/$name/SOUL.md"
  cat > "$path" <<EOF
# $name (two-bot demo profile — LIVE HERMES_HOME)

You drive the **$body_name** Mineflayer bot. Your MC env (\`MC_API_URL\`,
\`MC_USERNAME\`) is pinned in this profile's \`.env\` so every \`mc\` call
lands on $body_name and only $body_name.

You are a kanban worker on the **two-bot-demo** board for the cooperative
base demo. Cards come from \`prototypes/agent-arch/capstone/two_bot_base_graph.py\`
and carry a \`[bot:$body_name]\` title prefix. Read which role this card
asks (@navigator, @builder, @crafter, @miner) and load that role's bundle.

## Turn 1

Call \`skill_view('agent-<role>')\` where <role> is one of:
navigator, builder, crafter, miner. Then \`mc status\` to confirm position
and inventory.

## Talking to the world

\`\$MC_API_URL\` is pinned to $body_name's port. Always use the \`mc\` CLI.

## Cooperation

You're one of two pilots on this board. The other bot runs its own lane.
Read parent handoff metadata (\`exit_pos\`, \`inv_delta\`, \`work_at_mark\`)
before acting. If a partner bot is blocking your placement, see
\`agent-builder.md\` §4 "Coordinating with a partner bot".

## Block, don't retry

Verb fails twice without progress → \`kanban_block\` with a structured
reason from the role bundle's §5. The other lane stays productive.
EOF
  log "wrote $path"
}

# ── Profile creation ────────────────────────────────────────────────

create_profile pilot-pip \
  "Pilot bound to bot Pip (port 3005). Two-bot demo on live HERMES_HOME, dashboard-visible. Plays @navigator, @builder, @crafter, @miner per card."
write_config_yaml pilot-pip
write_env_from_template pilot-pip "$SCRIPT_DIR/profiles_pilot-pip.env.template"
install_skills pilot-pip "${SKILL_SOURCES[@]}"
write_soul pilot-pip Pip

create_profile pilot-zee \
  "Pilot bound to bot Zee (port 3006). Two-bot demo on live HERMES_HOME, dashboard-visible. Plays @navigator, @builder, @crafter, @miner per card."
write_config_yaml pilot-zee
write_env_from_template pilot-zee "$SCRIPT_DIR/profiles_pilot-zee.env.template"
install_skills pilot-zee "${SKILL_SOURCES[@]}"
write_soul pilot-zee Zee

log "done."
log "  HERMES_HOME    = $HERMES_HOME"
log "  profiles dir   = $PROFILES_DIR"
log "  pilots         = pilot-pip pilot-zee"
log
log "Trial 3 launch (visible on http://127.0.0.1:9119 dashboard):"
log "  HERMES_HOME=$HERMES_HOME \\"
log "    python prototypes/agent-arch/capstone/run_two_bot_base.py \\"
log "    --run-id trial-\$(date +%s) --board two-bot-demo --watch"
log
log "Verify:"
log "  HERMES_HOME=$HERMES_HOME hermes profile show pilot-pip"
log "  HERMES_HOME=$HERMES_HOME hermes kanban --board two-bot-demo list"
